### ISSUE TITLE
web version cannot run

### ISSUE THREAD

**Issue by AoEiuV020** [vishnuagbly/google_sign_in_all_platforms#5]
```
org-dartlang-app:/web_plugin_registrant.dart:9:8: Error: Error when reading '/Users/aoeiuv/.pub-cache/hosted/pub.dev/google_sign_in_all_platforms_mobile-0.0.1/lib/google_sign_in_all_platforms_mobile_web.dart': No such file or directory
import 'package:google_sign_in_all_platforms_mobile/google_sign_in_all_platforms_mobile_web.dart';
       ^
org-dartlang-app:/web_plugin_registrant.dart:17:3: Error: Undefined name 'GoogleSignInAllPlatformsMobileWeb'.
  GoogleSignInAllPlatformsMobileWeb.registerWith(registrar);
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```

**Comment by vishnuagbly** [comment]
Hii.. sorry, missed your comment, can you provide the minimum reproducible code for it?

**Comment by AoEiuV020** [comment]
The example in this project doesn't work without any modifications. @vishnuagbly 
```shell
git clone --depth 1 --branch main git@github.com:vishnuagbly/google_sign_in_all_platforms.git && cd google_sign_in_all_platforms && cd google_sign_in_all_platforms/example && flutter pub get && flutter run -d chrome
```

**Comment by AoEiuV020** [comment]
<img width="908" alt="image" src="https://github.com/vishnuagbly/google_sign_in_all_platforms/assets/11682198/ae111316-d20e-4203-be1e-7026baf09bf3">

**Comment by vishnuagbly** [comment]
Got it 👍 , will have to look into it. I do not have a Windows PC, so has not been able to work properly on it.
While, @AoEiuV020 , if you can figure out the issue and create a PR, it would be great, I am looking for collaborators on this project 🙂 .

**Comment by lambiengcode** [comment]
pubspec.yaml
```yaml
web:
        pluginClass: GoogleSignInAllPlatformsMobileWeb
        fileName: google_sign_in_all_platforms_mobile_web.dart /// <--- I think this cause the problem, not found this file
        dartPluginClass: GoogleSignInAllPlatformsMobile
```
